# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sgh < Formula
  desc "Command-line tool for GitHub across repositories and organizations"
  homepage "https://github.com/pradyb/sgh-cli"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pradyb/sgh-cli/releases/download/v1.4.0/sgh_1.4.0_darwin_amd64.tar.gz"
      sha256 "f2f337b280cb53201e0318c3712f46afabe90e69a3fc6a6fbf7647727b1d5ac9"

      define_method(:install) do
        bin.install "sgh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pradyb/sgh-cli/releases/download/v1.4.0/sgh_1.4.0_darwin_arm64.tar.gz"
      sha256 "1015d1f36213d6c99ed9cf7c3023dbbe1c4744e318a89fda90da105baffb77ee"

      define_method(:install) do
        bin.install "sgh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pradyb/sgh-cli/releases/download/v1.4.0/sgh_1.4.0_linux_amd64.tar.gz"
      sha256 "58a388e6bc8421defaf0604f3cc96cfae57fb750af1d54663096204ee6b54e5b"
      define_method(:install) do
        bin.install "sgh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pradyb/sgh-cli/releases/download/v1.4.0/sgh_1.4.0_linux_arm64.tar.gz"
      sha256 "0af2216dc21023bd0ba7b280ad3d8b52998c2848140d610fcefb69b390f89aec"
      define_method(:install) do
        bin.install "sgh"
      end
    end
  end

  test do
    # sgh refuses to run without a token, even for `version`; it only has to look like a ghp_ token.
    with_env(SGH_TOKEN: "ghp_dummyTokenForBrewTest0123456789abcdef") do
      assert_match version.to_s, shell_output("#{bin}/sgh version")
    end
  end
end
