# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sgh < Formula
  desc "Command-line tool for GitHub across repositories and organizations"
  homepage "https://github.com/pradyb/sgh-cli"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pradyb/sgh-cli/releases/download/v1.3.1/sgh_1.3.1_darwin_amd64.tar.gz"
      sha256 "51f4172ffbd299ed3d13398436d6f1f447a6dbae68137d29e04543c886cc8eac"

      define_method(:install) do
        bin.install "sgh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pradyb/sgh-cli/releases/download/v1.3.1/sgh_1.3.1_darwin_arm64.tar.gz"
      sha256 "b9abea30d747ecb2d66f73eb82a58aad7ac7935ae92f1500934cbbee7c7d2b89"

      define_method(:install) do
        bin.install "sgh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pradyb/sgh-cli/releases/download/v1.3.1/sgh_1.3.1_linux_amd64.tar.gz"
      sha256 "13024bf7d578e4ae9db674b9181cf35eb72c38e26d32b4f9005e328e9d97962a"
      define_method(:install) do
        bin.install "sgh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pradyb/sgh-cli/releases/download/v1.3.1/sgh_1.3.1_linux_arm64.tar.gz"
      sha256 "f7eaa262574e7da4cf75c5b9ad1bb515bb522997f66683d7b226151d92985422"
      define_method(:install) do
        bin.install "sgh"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sgh version")
  end
end
