# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sgh < Formula
  desc "Command-line tool for GitHub across repositories and organizations"
  homepage "https://github.com/pradyb/sgh-cli"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pradyb/sgh-cli/releases/download/v1.3.2/sgh_1.3.2_darwin_amd64.tar.gz"
      sha256 "f6606e78a6ec7730b989f385f44784c7df4fc314fa74bcaf6dfd4845830acaee"

      define_method(:install) do
        bin.install "sgh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pradyb/sgh-cli/releases/download/v1.3.2/sgh_1.3.2_darwin_arm64.tar.gz"
      sha256 "8bf3ae327e5e4a0d223d13a8644864eaa65539df1b4c3b7c55b2503797f3976f"

      define_method(:install) do
        bin.install "sgh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pradyb/sgh-cli/releases/download/v1.3.2/sgh_1.3.2_linux_amd64.tar.gz"
      sha256 "d569be1dc5d9621819fc46784100f99f7c6172166a28db954c3e89ff20d81c31"
      define_method(:install) do
        bin.install "sgh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pradyb/sgh-cli/releases/download/v1.3.2/sgh_1.3.2_linux_arm64.tar.gz"
      sha256 "47a5ebd35ba96e4cfb1bfdea89b3bee787bbd7b10932eee51fcaf267bf5d21c4"
      define_method(:install) do
        bin.install "sgh"
      end
    end
  end

  test do
    # sgh refuses to run without a token, even for `version`; it only has to look like a ghp_ token.
    with_env(SGH_TOKEN: "ghp_dummyTokenForBrewTest0123456789abcdef") do
      assert_match version.to_s, shell_output("#{bin}/sgh version")
    end
  end
end
